# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61aa85eb4f980120f1275c083bc31149"
name = "image-banner-extension"
handle = "image-banner-extension-1"
application_url = "https://beth-oasis-examining-jaguar.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "banner.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://beth-oasis-examining-jaguar.trycloudflare.com/auth/callback",
  "https://beth-oasis-examining-jaguar.trycloudflare.com/auth/shopify/callback",
  "https://beth-oasis-examining-jaguar.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
