# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0dfab5cb647ba76b55768bdd6730a2d7"
name = "banner-image"
handle = "banner-image-4"
application_url = "https://fig-wells-views-moves.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "digifist-image-banner.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://fig-wells-views-moves.trycloudflare.com/auth/callback",
  "https://fig-wells-views-moves.trycloudflare.com/auth/shopify/callback",
  "https://fig-wells-views-moves.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
